const logError = async exception => {
    //  TODO:   @olivermontalvanm   Mejorar este método de bitácora de errores.
    console.error(exception);
};

export {
    logError,
};